insert into "ingredienti" ("nome") values ('Pasta');
insert into "ingredienti" ("nome") values ('Uova');
insert into "ingredienti" ("nome") values ('Guanciale');
insert into "ingredienti" ("nome") values ('Pecorino Romano');
insert into "ingredienti" ("nome") values ('Vitello');
insert into "ingredienti" ("nome") values ('Prosciutto crudo');
insert into "ingredienti" ("nome") values ('Salvia');
insert into "ingredienti" ("nome") values ('Mascarpone');
insert into "ingredienti" ("nome") values ('Cacao');
insert into "ingredienti" ("nome") values ('Mozzarella');
insert into "ingredienti" ("nome") values ('Basilico');
insert into "ingredienti" ("nome") values ('Pomodoro');
insert into "ingredienti" ("nome") values ('Funghi');
insert into "ingredienti" ("nome") values ('Olive');
insert into "ingredienti" ("nome") values ('Riso');
insert into "ingredienti" ("nome") values ('Pesce crudo');
insert into "ingredienti" ("nome") values ('Tofu');
insert into "ingredienti" ("nome") values ('Verdure');
insert into "ingredienti" ("nome") values ('Gamberi');
insert into "ingredienti" ("nome") values ('Frutta e verdura');
insert into "ingredienti" ("nome") values ('Frutti di bosco');
insert into "ingredienti" ("nome") values ('Pasta frolla');
insert into "ingredienti" ("nome") values ('Cioccolato');
insert into "ingredienti" ("nome") values ('Mandorle');
