insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Pasta con uova, guanciale e pecorino romano', 'Spaghetti alla Carbonara', 1, '10.50', 1);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Fettine di vitello con prosciutto crudo e salvia', 'Saltimbocca alla Romana', 2, '15.00', 1);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Dolce italiano al caffè con mascarpone e cacao', 'Tiramisù', 3, '7.00', 1);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Pizza con pomodoro, mozzarella e basilico', 'Pizza Margherita', 4, '8.00', 2);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Pizza con pomodoro, mozzarella, prosciutto cotto, funghi e olive', 'Pizza Capricciosa', 5, '10.00', 2);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Pizza chiusa a forma di mezzaluna con ripieno di pomodoro e mozzarella', 'Calzone', 6, '9.50', 2);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Torta al cioccolato e mandorle tipica della tradizione partenopea', 'Torta Caprese', 7, '6.50', 2);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Assortimento di pesce crudo tagliato a fettine', 'Sashimi Misto', 8, '18.00', 3);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Sushi con riso e pezzo di pesce crudo o altro ingrediente sopra', 'Nigiri Sushi', 9, '4.50', 3);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Frittura giapponese di gamberi e verdure in pastella croccante', 'Tempura', 10, '12.00', 3);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Tiramisù al tè verde matcha giapponese', 'Matcha Tiramisu', 11, '8.50', 3);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Hamburger con carne di manzo, lattuga, pomodoro e salsa', 'Hamburger Classico', 12, '7.00', 4);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Hamburger con formaggio cheddar fuso', 'Cheeseburger', 13, '8.00', 4);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Patatine tagliate a bastoncino e fritte', 'Patatine Fritte', 14, '3.50', 4);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Insalata mista con verdure fresche e tofu', 'Insalata Vegana', 15, '9.00', 5);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Lasagne con ragù di verdure e besciamella', 'Lasagne Vegetariane', 16, '11.50', 5);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Frullato di frutta e verdura per purificare il corpo', 'Smoothie Detox', 17, '6.50', 5);
insert into "piatti" ("descrizione", "nome", "piatto_id", "prezzo", "restaurant_id") values ('Dolce con base di pasta frolla e frutti di bosco freschi', 'Crostata ai Frutti di Bosco', 18, '5.50', 5);
