insert into "allergeni" ("nome") values ('glutine');
insert into "allergeni" ("nome") values ('crostacei');
insert into "allergeni" ("nome") values ('uova');
insert into "allergeni" ("nome") values ('pesce');
insert into "allergeni" ("nome") values ('arachidi');
insert into "allergeni" ("nome") values ('soia');
insert into "allergeni" ("nome") values ('latte');
insert into "allergeni" ("nome") values ('frutta a guscio');
insert into "allergeni" ("nome") values ('sedano');
insert into "allergeni" ("nome") values ('senape');
insert into "allergeni" ("nome") values ('sesamo');
insert into "allergeni" ("nome") values ('anidride solforosa');
insert into "allergeni" ("nome") values ('lupini');
insert into "allergeni" ("nome") values ('molluschi');
